const constants = {
    FIELD_WIDTH: 40,
    FIELD_HEIGHT: 24,

    GAME_WINDOW_WIDTH: 21,
    GAME_WINDOW_HEIGHT: 13,

    MIN_ROOMS: 3,
    MAX_ROOMS: 8,
    MIN_WIDTH_ROOM: 5,
    MIN_HEIGHT_ROOM: 5,
    MAX_WIDTH_ROOM: 10,
    MAX_HEIGHT_ROOM: 10,

    PERSON_ATTACK_POWER: 25,
    ENEMY_ATTACK_POWER: 10,
    LIFE_HEALTH: 100,
    HEALTH_UP: 50,
    ATTACK_MULTIPLICATION: 2.1,
    ENEMIES_QUANTITY: 10,
    SWORDS_QUANTITY: 2,
    HEALTHS_UP_QUANTITY: 10,
};

export default constants;
